---
# Elasticsearch Ansible Playbook

- hosts: pythonapp
  sudo: yes
  roles:
    - web
  vars:
    - update_apt_cache: yes
    - application_name: myapp

    #Web
    - app_root: '/webapps/{{ application_name }}'
    - git_root: '{{ app_root }}/{{ application_name }}'
    - virtualenv_path: '{{ git_root }}/venv'
    - requirements_file: '{{ git_root }}/requirements.txt'

    #(Web) Git
    - setup_git_repo: yes
    - git_repo: 'git@github.com:/getgoing/airborne.git'
    - git_branch: 'release.5.3.0'
    - git_private_key: '/Users/mark/.ssh/id_vagrant_github'
    - git_public_key: '/Users/mark/.ssh/id_vagrant_github.pub'

    # #(Web) Gunicorn
    # - gunicorn_user: '{{ application_user }}'
    # - gunicorn_group: '{{ application_group }}'
    # - gunicorn_num_workers: 1
    # - gunicorn_max_requests: 0

    # #(Web) Django
    # - django_settings_file: '{{ application_name }}.live_settings'
    # - django_secret_key: ''
    # - run_django_syncdb: yes
    # - run_django_migrations: yes
    # - run_django_collectstatic: yes

    #(Web) Nginx
    # - nginx_server_name: localhost
    # - nginx_http_port: 80
    # - nginx_https_port: 443
    # - nginx_access_log_file: "{{ application_log_dir }}/nginx/nginx_access.log"
    # - nginx_error_log_file: "{{ application_log_dir }}/nginx/nginx_error.log"
    # - nginx_static_dir: "{{ git_root }}/static/"
    # - nginx_media_dir: "{{ git_root }}/media/"
