- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - git
    - python-dev
    - python-pip
    - libpq-dev
    - libjpeg8-dev
    - libxml2-dev
    - libxslt-dev
    - libmemcached-dev
    - libkyotocabinet-dev
  tags: packages

- name: Install virtualenv
  pip: name={{ item }}
  with_items:
    - virtualenv
  tags: packages
